[package]
name = "osterrain50"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.5.13"
walkdir = "2.3.2"
byteorder = "1"